def options(opt):
  opt.load('compiler_cxx')

def configure(conf):
  conf.env.CXXFLAGS += ['-O0', '-Wall', '-g', '-pipe']

  conf.load('compiler_cxx')
  conf.check_cfg(package = 'jubatus', args = '--cflags --libs')
  conf.check_cfg(package = 'liblog4cxx', args = '--cflags --libs')

def build(bld):
    bld.program(
      source = ['/src/main.cpp', 'src/logger.cpp'],
      target = 'logging-sample',
      includes = '.',
      use = [
          'JUBATUS',
          'LIBLOG4CXX',
      ]
    )
